samples: "config/samples.tsv"

params:
  adapterremoval: 
    extra: "--maxns 1 --minlength 50 --minquality 30 --gzip --trimqualities"
    adapter1: "--adapter1 AGATCGGAAGAGC"
  bowtie2:
    extra: ""
  samtools:
    sort: "-m 4G"
    index: ""
  markduplicates:
    extra: "--REMOVE_DUPLICATES true"

reference: 
  path: "/hpcfs/users/a1018048/refs/gencode-release-33/GRCh37/dna/bt2"
  index: "GRCh37.primary_assembly.genome"
