samples: "config/samples.tsv"

params:
  adapterremoval: 
    extra: "--maxns 1 --minlength 50 --minquality 30 --gzip --trimqualities"
    adapter1: "--adapter1 AGATCGGAAGAGC"
  bowtie2:
    extra: ""
  samtools:
    sort: "-m 4G"
    index: ""
  markduplicates:
    extra: "--REMOVE_DUPLICATES true"
  macs2:
    callpeak: "-f BAM -g hs --keep-dup -q 0.05 --bdg --SPMR"
    bdgcmp: "-m FE"

reference: 
  path: "/data/tki_bodl/data/references/gencode_v41/GRCh37/bwt2/"
  index: "GRCh37"
