samples: "config/PRJNA509779.tsv"

paths:
  fastq: "data/fastq"
  aligned: "data/aligned"
  deduplicated: "data/deduplicated"
  macs2: "output/macs2"
  qc: "docs/qc"

params:
  adapterremoval:
    extra: "--maxns 1 --minlength 50 --minquality 30 --gzip --trimqualities"
    adapter1: "--adapter1 AGATCGGAAGAGC"
  bowtie2: ""
  fastqc: "--nogroup --noextract"
  macs2:
    callpeak: "-g hs --keep-dup all -q 0.05"
    bdgcmp: "-m FE"
  markduplicates: "--REMOVE_DUPLICATES true"
  multiqc: ""
  samtools:
    sort: ""
    view: "-q2"
    index: ""

reference:
  path: "/Volumes/Accelsior-4M2/shared/reference_genomes/Homo_sapiens/GENCODE_v41/GRCh37/bwt2/"
  index: "GRCh37"
  name: "GRCh37"
